services:
  - type: web
    name: academic-bot-production
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: API_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SUPER_ADMIN_ID
        value: "6842543527"
      - key: STORAGE_CHANNEL_ID
        value: "-1003769719318"
